<div style="width:500px; height:500px; margin: auto; margin-top:100px;"> 
    <div style=" float:left;display:inline-block; position:relative; width:150px;"> 
   		 <img  src="images/frog.png">
    </div>
    <div style=" float:left;display:inline-block; position:relative; width:300px;"> 
		<span style="font-size:40px;text-indent:20px;">&nbsp;&nbsp;Error</span><br>
        <span style="font-size:100px;">404</span>
	</div>
    <div style=" float:left;display:inline-block; position:relative; width:500px;"> 
<h1 style="color:#383737"> Frog just Encountered a problem </h1>
<h2> <a style="color:#214f75;text-decoration:none;" href="<?php echo $this->baseUrl("/") ?>">Leap back to home</a></h2>
</div>
</div>