<?php
    echo $this->form;
?>
<!--<div>
    <form name="addContent" action="/admin/addcontent" method="post">
        
    <div>   
    <label>Menu:</label>
    <select name="menu">
        <option>About</option>
        <option>Admissions</option>
        <option>Departments</option>
    </select>
    </div>
        
    <div>
    <label>Title: </label>
    <input type="text" name="title">
    </div>
    
    <div>    
    <label>Content</label><br>
    <textarea cols="40" rows="10" name="content">

    </textarea>
    </div>
        
    <div>
    <label>Status</label>
    <input type="checkbox" name="status" checked="true">
    </div>
        
    <div>
    <input type="submit" name="add" value="Add Content">
    </div>

    </form>
</div>

--!>