<?php

//echo $this->show;
//echo "sdf;lksdafj;ds";
$totalcontent =  $this->page;
$id = $totalcontent[0];
$title = $totalcontent[1];
$content = $totalcontent[2];
if($content == NULL){
    echo '<div style = "width:500px; margin: 0px auto;">';
    echo '<h1> No content is available this time</h1>';
    echo '<h2> Please visit our other pages</h2></div>';
    
} 
?>

<div id="contentother">
    <div id="admissioncontent">
         
    <div class="smenu">
        <script>
        function checkDelete(){
            var x =confirm("Do you really want to delete?");
            return x;
        }
        </script>
        <ul>
            <?php 
            $i=0;
            foreach ($title as $value) {

                echo '<li><a href="#'.$value.'">'.$value.'</a><br>
                    <a style="color:#214f75;" href="/cms/index/update/id/'.$id[$i].'">(<i>Edit</i>)</a>
                    <a onclick=" return checkDelete();" style="color:#214f75;" href="/cms/index/delete/id/'.$id[$i].'">(<i>Delete</i>)</a><br>&nbsp;</li>';
            
                $i++;
            }
            ?>
        </ul>
    </div>
    
    <div class="scont">
        <?php
        $i=0;
        foreach ($content as $value) {

                echo '<h2><a name="'.$title[$i].'">'.$title[$i].'</a></h1>';
                echo '<p>'.$value.'</p>';
                $i++;
            }
        
        ?>
    </div>
    </div>
</div>
     
     
     
     
     
     <?php
     /*
if($page == 'home' || $page == 'about' || $page == 'gallery'){

    echo"<h1>".$page."</h1>"; 
}
else
    echo"<h1>No page Found</h1>";
 * 
 */
?>
