
<!DOCTYPE html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
<title>LFTC :: Home</title>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css')) ?>
<!--<link href="css/style.css" rel="stylesheet" type="text/css" >
<link href="css/js-image-slider.css" rel="stylesheet" type="text/css" />
    <script src="js/js-image-slider.js" type="text/javascript"></script>
<script type="text/javascript" src="js/jquery.js"></script>
<script type="text/javascript" src="js/nav.js"></script>-->
</head>

<body>

<div id="header">
	<div id="title">
		<div id="logo">
			<a href="index.html" style="text-decoration:none;"><img src="/images/logo.png" alt="logo" style="border:none;"></a>
		</div>
		
		<form action="#">
		<div id="searchbox">
			<input type="text" id="textbox" placeholder="Search LFTC">
			<button type="submit" id="search" value="search">submit</button>
		</div>
		</form>    

	</div>
</div>
	




<div id="content">
  
    
    <div id="middle">
        
    
<?php echo $this->layout()->content ?>
</div>
    </div>
<div id="footercontainer">
    <div id="footer">
    	<div id="contact">
            <h2>Get in Touch</h2>
            <p>
            Telephone:+977 - 01- 5534403<br>
            Fax:+977 1 5534456<br>
            P.O.Box: 5645, Kupondole, Kathmandu<br>
            E-mail:info@lftc.edu.np<br>
            Kupondole, Kathmandu, Nepal
            </p>
        </div>
        <div id="social">
        <h2>Get Connected</h2>
        <div id="facebook">
        <img src="/images/faceb.png" title="facebook" alt="facebook" height="50px" width="50px">
        </div>
        <div id="twitter">
        <img src="/images/twitterb.png" title="twitter" alt="twitter"  height="50px" width="50px">
        </div>
        <div id="linkedin">
        <img src="/images/linkedinb.png" title="linkedin" alt="linkedin" height="50px" width="50px"><br>
        </div>
        <div id="youtube">
        <img src="/images/youtubelogob.png" title="youtube" alt="youtube"  height="50px" width="50px"><br>
        </div>
        </div>
        <div id="misc">
        <h2>Misc</h2>
        <p>
        Sitemap<br>
        Terms and conditions<br>
        Privacy Policy<br>
        Career options
        </p>
        </div>
    </div>
</div>
<div id="copyright">(C) Leapfrog Technology College, a college wing of Leapfrog Technology Inc.</div>

</body>
</html>
