<div id="content1">
<!--<div id="slides">slides slides></div>-->
<div id="sliderFrame">
<div id="ribbon"></div>
        <div id="slider">
            
			<img src="/images/new/funtime.jpg" alt="#Fun"/>
            <img src="/images/new/image-slider-1.jpg" alt="#Sports" />
            
            <img src="/images/new/image-slider-2.jpg" alt="#Food" />
            <img src="/images/new/image-slider-3.jpg" alt="#Classrooms" />
            <img src="/images/new/image-slider-4.jpg" alt="#Building" />
            <img src="/images/new/image-slider-5.jpg" alt="#Graduate"/>
			<img src="images/new/image-slider-6.jpg" alt="#Lab" />
            <img src="/images/new/image-slider-7.jpg" alt="#Research"/>
        </div>
        <div id="Fun" style="display: none;">
            <b><font size=+1>Fun time</font></b><br>Staffs and Faculty members enjoying the annual picnic.
        </div>
        <div id="Sports" style="display: none;">
            <b><font size=+1>Excellent in Sports</font></b><br>We have well equipped basketball court and have won 3 intercollege basketball tournaments.
        </div>
        <div id="Food" style="display: none;">
            <b><font size=+1>Quality and Hygenic Food</font></b><br>We believe better food makes us better person so our canteen provides healthy meals with various options.
        </div>
        <div id="Classrooms" style="display: none;">
            <b><font size=+1>Classrooms</font></b><br>We have state of the art classrooms including latest teaching methodologies.
        </div>
        <div id="Building" style="display: none;">
            <b><font size=+1>New is better</font></b><br>We are ready to move in our new building at the heart of kathmandu.
        </div>
        <div id="Graduate" style="display: none;">
            <b><font size=+1>Graduate with Flying Colors</font></b><br>Yearly 200+ students graduate from our college.
        </div>
         <div id="Lab" style="display: none;">
            <b><font size=+1>Lab Facilities at Its Peak</font></b><br>We also have state of the art labs and equipments so that the students never feel lagging in technological adaptation.
        </div>
        <div id="Research" style="display: none;">
            <b><font size=+1>Research In Progress</font></b><br>We do not stop; having Nepal's best research facility, we are continuously reasearching on various technological innovations. 
        </div>
    </div>

</div>
<div id="content2container">
<div id="content2">
	<div id="eventcontainer"> 
			<h2>EVENTS</h2>
                    <div id="events">
                    
                    <div id="eventsbox"> 
                      
						<h3><span class="event_month">MAR</span> <span class="event_day">22</span></h3>
						<div class="event_list">
						<p><span class="event_title"><a href="#" class="event-box" rel="width:600 height:800">Project Submission for PHP</a></span><br><span class="event_time">11:59 p.m.</span></p>
						</div>
						
						<h3><span class="event_month">MAR</span> <span class="event_day">25</span></h3>
						<div class="event_list">
						<p><span class="event_title"><a href="#" class="event-box" rel="width:600 height:800">PHP presentation</a></span><br><span class="event_time">1:30 p.m.</span></p>
						</div>
						
						<h3><span class="event_month">MAR</span> <span class="event_day">29</span></h3>
						<div class="event_list">
						<p><span class="event_title"><a href="#" class="event-box" rel="width:600 height:800">Java project submit</a></span><br><span class="event_time">11:59 p.m.</span></p>
						</div>
             
                    </div>
					
                    <!-- End events -->
                    <p class="more"><a href="404.html"><i>Event Calendar »</i></a></p>
                          </div>
      </div>
    
	<div id="contentmid"> 
		<div id="newscontainer">
        	<h2>COLLEGE NEWS</h2>
            <div id="news">
            
        	<p><img src="/images/news/football.jpg" height="50px">"Our College Football team just won the intercollege football tournament 2013"
            ....<a href="404.html"><i>Learn More »</i></a></p>
            
            <p style="padding-top:5px; border-top:1px dashed #265a85;"><img style="float:left; margin-top:-10px; padding-top:-10px;" src="/images/news/itpark.jpg" height="50px">"Students from our College visited IT PARK, Banepa"
            ....<a href="404.html"><i>Learn More »</i></a></p>
            
            </div>
        </div>
        <div id="researchcontainer">
        	<h2>RESEARCH</h2>
            <div id="research">
                <img src="/images/research/research-image-1.jpg" alt="Research on Robotic Limb control" height="100px"
                 title="Robotic Limb control" width="100px">
                <img src="/images/research/research-image-2.jpg" alt="Research on long distance encrypted communication"
                 height="100px" title="Long distance encrypted Communication" width="100px">
                <img src="/images/research/research-image-3.jpg" alt="Research on mobile based computer control" height="100px"
                 title="mobile based computer control" width="100px">
                <img src="/images/research/research-image-4.jpg" alt="Research on AI " height="100px" 
                title="Artificial Intelligence" width="100px">
                </div>
        </div>
	</div>
    <div id="lifecontainer">
    <h2>MESSAGE FROM PRINCIPAL</h2>
    <div id="life">
    	<img src='/images/principal.jpg'>
		<p>"I am deeply humbled for being entrusted the responsibility to lead this esteemed institution that rests on the foundation laid by the visionary team of pioneers who dared to dream differently. They, along with the steadfast support of countless well wishers including but not limited to students, parents, staffs, faculties, local, national and international supporters from all walks of life have made Leapfrog College"....<a href="404.html"><i>More »</i></a></p>
    </div>
    </div>

</div>
</div>