<!DOCTYPE html>
<head>
    <title>Leapfrog Technology College</title>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/style.css')) ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/js-image-slider.css')) ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('/js/js-image-slider.js')) ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('/js/jquery.js')) ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl('/js/nav.js') )?>
</head>
<body>
    
    
    </div>
<div id="header">
	<div id="title">
		<div id="logo">
			<img src="<?php echo $this->baseUrl();?>/images/logo.png" alt="logo" style="border:none;">
		</div>
		
		
		<div style="float: left; padding-left: 200px;color: white;font-family: Copperplate Gothic Light;font-size: 20px;">
                    <h1>Login Page</h1>
		</div>
		    

	</div>
</div>
	

</div> 
    



<?php echo $this->layout()->content ?>



</body>
</html>